2025-03-26 11:56:23,573 ERROR: 404 Error: http://127.0.0.1:5000/favicon.ico [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:90]
2025-03-26 12:20:41,761 ERROR: 404 Error: http://127.0.0.1:5000/search.html [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:90]
2025-03-26 12:25:13,512 ERROR: 404 Error: http://127.0.0.1:5000/search.html [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:90]
2025-03-26 12:34:05,131 ERROR: 404 Error: http://127.0.0.1:5000/search.html [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:90]
2025-03-26 12:34:19,055 ERROR: 404 Error: http://127.0.0.1:5000/search.html [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:90]
2025-03-26 13:00:42,166 ERROR: Exception on / [GET] [in /home/gachuuri/.local/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/gachuuri/Building/Eco-Connect/app/routes/home.py", line 7, in home
    return render_template('landingpage.html')
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/gachuuri/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/gachuuri/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/home/gachuuri/.local/lib/python3.10/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/gachuuri/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/gachuuri/.local/lib/python3.10/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/home/gachuuri/.local/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gachuuri/Building/Eco-Connect/app/templates/landingpage.html", line 34, in template
    <img src="{{ url_for('static', screenshots/eco-login.png') }}" alt="Feature 1" class="img-fluid">
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'string'
2025-03-26 13:00:42,238 CRITICAL: 500 Internal Server Error at http://127.0.0.1:5000/ - Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:95]
2025-03-26 15:24:22,139 ERROR: 404 Error: http://127.0.0.1:5000/search.html [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:90]
2025-03-26 16:41:51,955 ERROR: 404 Error: http://127.0.0.1:5000/search.html [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:90]
2025-03-26 16:43:05,690 ERROR: 404 Error: http://127.0.0.1:5000/register.html [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:90]
2025-03-26 16:43:14,455 ERROR: 404 Error: http://127.0.0.1:5000/register.html [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:90]
2025-03-26 17:18:14,814 ERROR: Exception on /api/auth/login [POST] [in /home/gachuuri/.local/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gachuuri/.local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/gachuuri/Building/Eco-Connect/app/routes/auth.py", line 60, in login
    {'user_id': user.id, 'exp': datetime.now(datetime.timezone.utc) + timedelta(hours=3)},
AttributeError: type object 'datetime.datetime' has no attribute 'timezone'
2025-03-26 17:18:14,860 CRITICAL: 500 Internal Server Error at http://127.0.0.1:5000/api/auth/login - Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in /home/gachuuri/Building/Eco-Connect/app/__init__.py:95]
